# Generated by Django 3.2.7 on 2022-01-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('ComplainNo', models.AutoField(primary_key=True, serialize=False)),
                ('Complainer', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Complain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='', max_length=30)),
                ('Last_Name', models.CharField(default='', max_length=30)),
                ('User_Name', models.CharField(default='', max_length=30)),
                ('Phone_Number', models.CharField(default='', max_length=30)),
                ('NID', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='employee_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('date', models.DateField()),
                ('no_of_tickets', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='', max_length=30)),
                ('Last_Name', models.CharField(default='', max_length=30)),
                ('User_Name', models.CharField(default='', max_length=30)),
                ('Phone_Number', models.CharField(default='', max_length=30)),
                ('NID', models.CharField(default='', max_length=30)),
                ('Package', models.CharField(default='', max_length=30)),
                ('Pay_With', models.CharField(max_length=30)),
                ('Card_Num', models.CharField(default='', max_length=30)),
                ('Start_Date', models.DateField(auto_now=True)),
                ('Card_Status', models.CharField(default='', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedule_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=200, null=True)),
                ('source', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('arrival_time', models.TimeField(null=True)),
                ('departure_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSell',
            fields=[
                ('ticketNo', models.IntegerField(primary_key=True, serialize=False)),
                ('ticketSource', models.CharField(max_length=70)),
                ('ticketDestination', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('noOfTicket', models.IntegerField()),
                ('total', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TrainFare',
            fields=[
                ('trainid', models.IntegerField(primary_key=True, serialize=False)),
                ('trainname', models.CharField(max_length=70)),
                ('trainsource', models.CharField(max_length=70)),
                ('traindestination', models.CharField(max_length=70)),
                ('trainarrival', models.TimeField()),
                ('trainreach', models.TimeField()),
                ('trainfare', models.IntegerField(null=True, unique=True)),
            ],
        ),
    ]
