# Generated by Django 3.2.7 on 2021-12-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schedule',
            new_name='schedule_check',
        ),
    ]
