# Generated by Django 4.0 on 2021-12-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schedule_check',
        ),
    ]
