# Generated by Django 4.0 on 2022-01-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('ComplainNo', models.AutoField(primary_key=True, serialize=False)),
                ('Complainer', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Complain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketSell',
            fields=[
                ('ticketNo', models.IntegerField(primary_key=True, serialize=False)),
                ('ticketSource', models.CharField(max_length=70)),
                ('ticketDestination', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('noOfTicket', models.IntegerField()),
                ('total', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TrainFare',
            fields=[
                ('trainid', models.IntegerField(primary_key=True, serialize=False)),
                ('trainname', models.CharField(max_length=70)),
                ('trainsource', models.CharField(max_length=70)),
                ('traindestination', models.CharField(max_length=70)),
                ('trainarrival', models.TimeField()),
                ('trainreach', models.TimeField()),
                ('trainfare', models.IntegerField(null=True, unique=True)),
            ],
        ),
    ]
