# Generated by Django 4.0 on 2021-12-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0002_rename_schedule_schedule_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='', max_length=30)),
                ('Last_Name', models.CharField(default='', max_length=30)),
                ('Phone_Number', models.CharField(default='', max_length=30)),
                ('NID', models.CharField(default='', max_length=30)),
                ('Package', models.CharField(default='', max_length=30)),
                ('Pay_With', models.CharField(max_length=30)),
                ('Card_Num', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
