# Generated by Django 4.0 on 2021-12-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0003_premium_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium_member',
            name='User_Name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
