# Generated by Django 4.0 on 2021-12-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0003_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Premium_Member',
            new_name='PremiumMember',
        ),
    ]
