# Generated by Django 4.0 on 2021-12-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0004_premium_member_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schedule_check',
        ),
    ]
