# Generated by Django 3.2.7 on 2021-12-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0004_premium_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium_ticket',
            old_name='Card_Num',
            new_name='card_num',
        ),
        migrations.RenameField(
            model_name='premium_ticket',
            old_name='Card_Status',
            new_name='card_status',
        ),
        migrations.RenameField(
            model_name='premium_ticket',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='premium_ticket',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='premium_ticket',
            old_name='NID',
            new_name='nid',
        ),
        migrations.RenameField(
            model_name='premium_ticket',
            old_name='Package',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='premium_ticket',
            old_name='Pay_With',
            new_name='pay_with',
        ),
        migrations.RenameField(
            model_name='premium_ticket',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='premium_ticket',
            old_name='User_Name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='premium_ticket',
            name='start_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
