# Generated by Django 3.2.7 on 2021-12-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0006_rename_start_date_premium_ticket_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium_ticket',
            name='start_date',
            field=models.DateField(),
        ),
    ]
