# Generated by Django 3.2.7 on 2021-12-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0009_auto_20211226_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ticket',
            name='email_address',
            field=models.EmailField(default='example@email.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ticket',
            name='train_no',
            field=models.IntegerField(default=0),
        ),
    ]
