# Generated by Django 3.2.7 on 2021-12-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0011_rename_email_address_user_ticket_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('date', models.DateField()),
                ('no_of_tickets', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='user_ticket',
            old_name='train_no',
            new_name='ticket_no',
        ),
    ]
