# Generated by Django 3.2.7 on 2021-12-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0012_auto_20211227_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_ticket',
            old_name='train_no',
            new_name='ticket_no',
        ),
    ]
