# Generated by Django 4.0 on 2021-12-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainfare',
            fields=[
                ('trainid', models.IntegerField(primary_key=True, serialize=False)),
                ('trainname', models.CharField(max_length=70)),
                ('trainsource', models.CharField(max_length=70)),
                ('traindestination', models.CharField(max_length=70)),
                ('trainarrival', models.TimeField()),
                ('trainreach', models.TimeField()),
                ('trainfare', models.IntegerField(null=True, unique=True)),
            ],
        ),
    ]
