# Generated by Django 4.0 on 2021-12-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('ComplainNo', models.AutoField(primary_key=True, serialize=False)),
                ('Complainer', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Complain', models.TextField()),
            ],
        ),
    ]
