# Generated by Django 4.0 on 2021-12-24 10:17

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSell',
            fields=[
                ('ticketNo', models.IntegerField(primary_key=True, serialize=False)),
                ('ticketSource', models.CharField(max_length=70)),
                ('ticketDestination', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('noOfTicket', models.IntegerField()),
                ('total', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
