# Generated by Django 4.0 on 2022-01-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellticket',
            old_name='travel_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sellticket',
            old_name='destination_form',
            new_name='source',
        ),
    ]
